development:
  adapter: postgresql
  encoding: unicode
  database: graffpass_development
  pool: 5
  username: graffpass
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: graffpass_test
  pool: 5
  username: graffpass
  password: password
